# Generated by Django 3.0.3 on 2020-02-27 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logbook',
            name='created',
            field=models.DateField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='logbook',
            name='end_date',
            field=models.DateField(help_text='Deadline', null=True, verbose_name='Deadline'),
        ),
        migrations.AlterField(
            model_name='logbook',
            name='start_date',
            field=models.DateField(help_text='Start Date', null=True, verbose_name='Start Date'),
        ),
    ]
