# Generated by Django 3.0.3 on 2020-02-27 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0002_auto_20200227_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logbook',
            name='created',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
