# Generated by Django 3.0.3 on 2020-02-27 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0003_auto_20200227_2053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logbook',
            name='start_date',
        ),
    ]
