# Generated by Django 3.0.3 on 2020-02-27 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0004_remove_logbook_start_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logbook',
            old_name='update',
            new_name='updated',
        ),
    ]
