# Generated by Django 3.0.3 on 2020-02-28 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0005_auto_20200228_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logbook',
            name='docfile',
            field=models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='logs',
            name='docfile',
            field=models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/%d'),
        ),
    ]
