# Generated by Django 3.0.3 on 2020-02-28 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0007_auto_20200228_2038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='LogBook',
            new_name='logbook',
        ),
        migrations.AlterField(
            model_name='log',
            name='body',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
